### ISSUE TITLE
Is an HTTP rule engine a pattern you've seen elsewhere or is it invented here?

### ISSUE THREAD

**Issue by maccam912** [ikouchiha47/httparty#1]
First of all, sorry for a github issue. I found this on lobste.rs and haven't been invited, so can't comment there.

I have a need for something like this, and have so far struggled to find something that exists to accomplish this easily. I ended up building my own (company owned) solution, but I like the pattern here. Is there some body of literature I should go read to understand how others have done this or did you have to basically invent a solution yourself too?

Thanks!

**Comment by ikouchiha47** [comment]
No, I haven't seen solutions as such, or atleast any popular one.

Its just simple rule engines and state machines. I didn't find any popular library that does this. There are rule engines of course. But I guess this is a niche area. So lack of libraries sorta makes sense.
